name: sologs CI Build and Testing

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    name: Build and Run Tests (Docker)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t rem8cpp-test .

      - name: Run tests
        run: docker run --rm rem8cpp-test

